### ISSUE TITLE
ryft-server doesn't work with JSON array documents

### ISSUE THREAD

**Issue by Pilatuz** [getryft/ryft-server#203]
If JSON document is defined in RDF as array the output DATA file also contains JSON array: [ ... , ... ]
These format is unexpected for ryft server. Ryft server expects records (pieces of DATA) one-by-one with exactly the same length as specified by corresponding INDEX file. It doesn't expect additional `[` or `]` or `,`.

**Comment by adleyva** [comment]
Issue fixed
